//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Rut_Usuario { get; set; }
        public string Dv_Usuario { get; set; }
        public string Primer_Nombre { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Apellido_Materno { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Correo_Electronico { get; set; }
        public string Contrasena { get; set; }
        public Nullable<int> Intento_Login_Fallido { get; set; }
        public Nullable<int> Rut_Empresa { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Estado_Usuario Estado_Usuario { get; set; }
    }
}
